# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a54f8954134ab150d9971ae11c8c4722cfd5cda6280a74984ea96ae80b93798f387d831aced9cc760d650c49c367d0498d54a19dba83c2dcb0cc6027f953d54

test:
  secret_key_base: b8497bb3373655771525cfcf70f914a8c057c00f679dc50ce55c753d67c6bfa812b049e836d16c1e994574ada3f37de4bff76b4d2c6e7e92d38ca1e433fd5e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
